// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tasks/tasks.proto

package tasks // import "github.com/duolacloud/microbase/proto/tasks"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import api "github.com/duolacloud/microbase/proto/api"
import durationpb "google.golang.org/protobuf/types/known/durationpb"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamppb.Timestamp

// Duration from public import google/protobuf/duration.proto
type Duration = durationpb.Duration

type HttpMethod int32

const (
	HttpMethod_HTTP_METHOD_UNSPECIFIED HttpMethod = 0
	HttpMethod_POST                    HttpMethod = 1
	HttpMethod_GET                     HttpMethod = 2
	HttpMethod_HEAD                    HttpMethod = 3
	HttpMethod_PUT                     HttpMethod = 4
	HttpMethod_DELETE                  HttpMethod = 5
	HttpMethod_PATCH                   HttpMethod = 6
	HttpMethod_OPTIONS                 HttpMethod = 7
)

var HttpMethod_name = map[int32]string{
	0: "HTTP_METHOD_UNSPECIFIED",
	1: "POST",
	2: "GET",
	3: "HEAD",
	4: "PUT",
	5: "DELETE",
	6: "PATCH",
	7: "OPTIONS",
}
var HttpMethod_value = map[string]int32{
	"HTTP_METHOD_UNSPECIFIED": 0,
	"POST":                    1,
	"GET":                     2,
	"HEAD":                    3,
	"PUT":                     4,
	"DELETE":                  5,
	"PATCH":                   6,
	"OPTIONS":                 7,
}

func (x HttpMethod) String() string {
	return proto.EnumName(HttpMethod_name, int32(x))
}
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{0}
}

type Task_View int32

const (
	Task_UNSPECIFIED Task_View = 0
	Task_BASIC       Task_View = 1
	Task_FULL        Task_View = 2
)

var Task_View_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "BASIC",
	2: "FULL",
}
var Task_View_value = map[string]int32{
	"UNSPECIFIED": 0,
	"BASIC":       1,
	"FULL":        2,
}

func (x Task_View) String() string {
	return proto.EnumName(Task_View_name, int32(x))
}
func (Task_View) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{9, 0}
}

type CreateTaskRequest struct {
	Parent               string        `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Task                 *Task         `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	ResponseView         *ResponseView `protobuf:"bytes,3,opt,name=responseView,proto3" json:"responseView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{0}
}
func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(dst, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *CreateTaskRequest) GetResponseView() *ResponseView {
	if m != nil {
		return m.ResponseView
	}
	return nil
}

type CreateTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{1}
}
func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(dst, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

type GetTaskRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{2}
}
func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (dst *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(dst, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

type GetTasksResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksResponse) Reset()         { *m = GetTasksResponse{} }
func (m *GetTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse) ProtoMessage()    {}
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{3}
}
func (m *GetTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse.Unmarshal(m, b)
}
func (m *GetTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse.Marshal(b, m, deterministic)
}
func (dst *GetTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse.Merge(dst, src)
}
func (m *GetTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse.Size(m)
}
func (m *GetTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse proto.InternalMessageInfo

type UpdateTaskRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{4}
}
func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(dst, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

type UpdateTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{5}
}
func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(dst, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

type ListTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{6}
}
func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (dst *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(dst, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

type ListTasksResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{7}
}
func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (dst *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(dst, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

type ResponseView struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseView) Reset()         { *m = ResponseView{} }
func (m *ResponseView) String() string { return proto.CompactTextString(m) }
func (*ResponseView) ProtoMessage()    {}
func (*ResponseView) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{8}
}
func (m *ResponseView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseView.Unmarshal(m, b)
}
func (m *ResponseView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseView.Marshal(b, m, deterministic)
}
func (dst *ResponseView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseView.Merge(dst, src)
}
func (m *ResponseView) XXX_Size() int {
	return xxx_messageInfo_ResponseView.Size(m)
}
func (m *ResponseView) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseView.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseView proto.InternalMessageInfo

type Task struct {
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScheduleTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduleTime,proto3" json:"scheduleTime,omitempty"`
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	DispatchDeadline *durationpb.Duration   `protobuf:"bytes,5,opt,name=dispatchDeadline,proto3" json:"dispatchDeadline,omitempty"`
	DispatchCount    int32                  `protobuf:"varint,6,opt,name=dispatchCount,proto3" json:"dispatchCount,omitempty"`
	ResponseCount    int32                  `protobuf:"varint,7,opt,name=responseCount,proto3" json:"responseCount,omitempty"`
	FirstAttempt     *Attempt               `protobuf:"bytes,8,opt,name=firstAttempt,proto3" json:"firstAttempt,omitempty"`
	LastAttempt      *Attempt               `protobuf:"bytes,9,opt,name=lastAttempt,proto3" json:"lastAttempt,omitempty"`
	View             Task_View              `protobuf:"varint,10,opt,name=view,proto3,enum=tasks.Task_View" json:"view,omitempty"`
	// Types that are valid to be assigned to PayloadType:
	//	*Task_HttpRequest
	//	*Task_PullMessage
	PayloadType          isTask_PayloadType `protobuf_oneof:"payloadType"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{9}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetScheduleTime() *timestamppb.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *Task) GetCreateTime() *timestamppb.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Task) GetDispatchDeadline() *durationpb.Duration {
	if m != nil {
		return m.DispatchDeadline
	}
	return nil
}

func (m *Task) GetDispatchCount() int32 {
	if m != nil {
		return m.DispatchCount
	}
	return 0
}

func (m *Task) GetResponseCount() int32 {
	if m != nil {
		return m.ResponseCount
	}
	return 0
}

func (m *Task) GetFirstAttempt() *Attempt {
	if m != nil {
		return m.FirstAttempt
	}
	return nil
}

func (m *Task) GetLastAttempt() *Attempt {
	if m != nil {
		return m.LastAttempt
	}
	return nil
}

func (m *Task) GetView() Task_View {
	if m != nil {
		return m.View
	}
	return Task_UNSPECIFIED
}

type isTask_PayloadType interface {
	isTask_PayloadType()
}

type Task_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,11,opt,name=httpRequest,proto3,oneof"`
}

type Task_PullMessage struct {
	PullMessage *PullMessage `protobuf:"bytes,12,opt,name=pullMessage,proto3,oneof"`
}

func (*Task_HttpRequest) isTask_PayloadType() {}

func (*Task_PullMessage) isTask_PayloadType() {}

func (m *Task) GetPayloadType() isTask_PayloadType {
	if m != nil {
		return m.PayloadType
	}
	return nil
}

func (m *Task) GetHttpRequest() *HttpRequest {
	if x, ok := m.GetPayloadType().(*Task_HttpRequest); ok {
		return x.HttpRequest
	}
	return nil
}

func (m *Task) GetPullMessage() *PullMessage {
	if x, ok := m.GetPayloadType().(*Task_PullMessage); ok {
		return x.PullMessage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Task) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Task_OneofMarshaler, _Task_OneofUnmarshaler, _Task_OneofSizer, []interface{}{
		(*Task_HttpRequest)(nil),
		(*Task_PullMessage)(nil),
	}
}

func _Task_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Task)
	// payloadType
	switch x := m.PayloadType.(type) {
	case *Task_HttpRequest:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpRequest); err != nil {
			return err
		}
	case *Task_PullMessage:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PullMessage); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Task.PayloadType has unexpected type %T", x)
	}
	return nil
}

func _Task_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Task)
	switch tag {
	case 11: // payloadType.httpRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HttpRequest)
		err := b.DecodeMessage(msg)
		m.PayloadType = &Task_HttpRequest{msg}
		return true, err
	case 12: // payloadType.pullMessage
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PullMessage)
		err := b.DecodeMessage(msg)
		m.PayloadType = &Task_PullMessage{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Task_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Task)
	// payloadType
	switch x := m.PayloadType.(type) {
	case *Task_HttpRequest:
		s := proto.Size(x.HttpRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Task_PullMessage:
		s := proto.Size(x.PullMessage)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HttpRequest struct {
	Url        string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HttpMethod HttpMethod        `protobuf:"varint,2,opt,name=httpMethod,proto3,enum=tasks.HttpMethod" json:"httpMethod,omitempty"`
	Headers    map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body       []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Types that are valid to be assigned to AuthorizationHeader:
	//	*HttpRequest_OauthToken
	//	*HttpRequest_OidcToken
	AuthorizationHeader  isHttpRequest_AuthorizationHeader `protobuf_oneof:"authorization_header"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{10}
}
func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (dst *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(dst, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HttpRequest) GetHttpMethod() HttpMethod {
	if m != nil {
		return m.HttpMethod
	}
	return HttpMethod_HTTP_METHOD_UNSPECIFIED
}

func (m *HttpRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type isHttpRequest_AuthorizationHeader interface {
	isHttpRequest_AuthorizationHeader()
}

type HttpRequest_OauthToken struct {
	OauthToken *OAuthToken `protobuf:"bytes,5,opt,name=oauthToken,proto3,oneof"`
}

type HttpRequest_OidcToken struct {
	OidcToken *OidcToken `protobuf:"bytes,6,opt,name=oidcToken,proto3,oneof"`
}

func (*HttpRequest_OauthToken) isHttpRequest_AuthorizationHeader() {}

func (*HttpRequest_OidcToken) isHttpRequest_AuthorizationHeader() {}

func (m *HttpRequest) GetAuthorizationHeader() isHttpRequest_AuthorizationHeader {
	if m != nil {
		return m.AuthorizationHeader
	}
	return nil
}

func (m *HttpRequest) GetOauthToken() *OAuthToken {
	if x, ok := m.GetAuthorizationHeader().(*HttpRequest_OauthToken); ok {
		return x.OauthToken
	}
	return nil
}

func (m *HttpRequest) GetOidcToken() *OidcToken {
	if x, ok := m.GetAuthorizationHeader().(*HttpRequest_OidcToken); ok {
		return x.OidcToken
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HttpRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HttpRequest_OneofMarshaler, _HttpRequest_OneofUnmarshaler, _HttpRequest_OneofSizer, []interface{}{
		(*HttpRequest_OauthToken)(nil),
		(*HttpRequest_OidcToken)(nil),
	}
}

func _HttpRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HttpRequest)
	// authorization_header
	switch x := m.AuthorizationHeader.(type) {
	case *HttpRequest_OauthToken:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OauthToken); err != nil {
			return err
		}
	case *HttpRequest_OidcToken:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OidcToken); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HttpRequest.AuthorizationHeader has unexpected type %T", x)
	}
	return nil
}

func _HttpRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HttpRequest)
	switch tag {
	case 5: // authorization_header.oauthToken
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OAuthToken)
		err := b.DecodeMessage(msg)
		m.AuthorizationHeader = &HttpRequest_OauthToken{msg}
		return true, err
	case 6: // authorization_header.oidcToken
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OidcToken)
		err := b.DecodeMessage(msg)
		m.AuthorizationHeader = &HttpRequest_OidcToken{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HttpRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HttpRequest)
	// authorization_header
	switch x := m.AuthorizationHeader.(type) {
	case *HttpRequest_OauthToken:
		s := proto.Size(x.OauthToken)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HttpRequest_OidcToken:
		s := proto.Size(x.OidcToken)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OAuthToken struct {
	ServiceAccount       string   `protobuf:"bytes,1,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthToken) Reset()         { *m = OAuthToken{} }
func (m *OAuthToken) String() string { return proto.CompactTextString(m) }
func (*OAuthToken) ProtoMessage()    {}
func (*OAuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{11}
}
func (m *OAuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthToken.Unmarshal(m, b)
}
func (m *OAuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthToken.Marshal(b, m, deterministic)
}
func (dst *OAuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthToken.Merge(dst, src)
}
func (m *OAuthToken) XXX_Size() int {
	return xxx_messageInfo_OAuthToken.Size(m)
}
func (m *OAuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthToken proto.InternalMessageInfo

func (m *OAuthToken) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

func (m *OAuthToken) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type OidcToken struct {
	ServiceAccount       string   `protobuf:"bytes,1,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	Audience             string   `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OidcToken) Reset()         { *m = OidcToken{} }
func (m *OidcToken) String() string { return proto.CompactTextString(m) }
func (*OidcToken) ProtoMessage()    {}
func (*OidcToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{12}
}
func (m *OidcToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OidcToken.Unmarshal(m, b)
}
func (m *OidcToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OidcToken.Marshal(b, m, deterministic)
}
func (dst *OidcToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OidcToken.Merge(dst, src)
}
func (m *OidcToken) XXX_Size() int {
	return xxx_messageInfo_OidcToken.Size(m)
}
func (m *OidcToken) XXX_DiscardUnknown() {
	xxx_messageInfo_OidcToken.DiscardUnknown(m)
}

var xxx_messageInfo_OidcToken proto.InternalMessageInfo

func (m *OidcToken) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

func (m *OidcToken) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

type PullMessage struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMessage) Reset()         { *m = PullMessage{} }
func (m *PullMessage) String() string { return proto.CompactTextString(m) }
func (*PullMessage) ProtoMessage()    {}
func (*PullMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{13}
}
func (m *PullMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMessage.Unmarshal(m, b)
}
func (m *PullMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMessage.Marshal(b, m, deterministic)
}
func (dst *PullMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMessage.Merge(dst, src)
}
func (m *PullMessage) XXX_Size() int {
	return xxx_messageInfo_PullMessage.Size(m)
}
func (m *PullMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PullMessage proto.InternalMessageInfo

func (m *PullMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PullMessage) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type Attempt struct {
	ScheduleTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=scheduleTime,proto3" json:"scheduleTime,omitempty"`
	DispatchTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=dispatchTime,proto3" json:"dispatchTime,omitempty"`
	ResponseTime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	ResponseStatus       *api.Status            `protobuf:"bytes,4,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Attempt) Reset()         { *m = Attempt{} }
func (m *Attempt) String() string { return proto.CompactTextString(m) }
func (*Attempt) ProtoMessage()    {}
func (*Attempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_81ac4b15a8391380, []int{14}
}
func (m *Attempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attempt.Unmarshal(m, b)
}
func (m *Attempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attempt.Marshal(b, m, deterministic)
}
func (dst *Attempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attempt.Merge(dst, src)
}
func (m *Attempt) XXX_Size() int {
	return xxx_messageInfo_Attempt.Size(m)
}
func (m *Attempt) XXX_DiscardUnknown() {
	xxx_messageInfo_Attempt.DiscardUnknown(m)
}

var xxx_messageInfo_Attempt proto.InternalMessageInfo

func (m *Attempt) GetScheduleTime() *timestamppb.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *Attempt) GetDispatchTime() *timestamppb.Timestamp {
	if m != nil {
		return m.DispatchTime
	}
	return nil
}

func (m *Attempt) GetResponseTime() *timestamppb.Timestamp {
	if m != nil {
		return m.ResponseTime
	}
	return nil
}

func (m *Attempt) GetResponseStatus() *api.Status {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateTaskRequest)(nil), "tasks.CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "tasks.CreateTaskResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "tasks.GetTaskRequest")
	proto.RegisterType((*GetTasksResponse)(nil), "tasks.GetTasksResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "tasks.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "tasks.UpdateTaskResponse")
	proto.RegisterType((*ListTasksRequest)(nil), "tasks.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "tasks.ListTasksResponse")
	proto.RegisterType((*ResponseView)(nil), "tasks.ResponseView")
	proto.RegisterType((*Task)(nil), "tasks.Task")
	proto.RegisterType((*HttpRequest)(nil), "tasks.HttpRequest")
	proto.RegisterMapType((map[string]string)(nil), "tasks.HttpRequest.HeadersEntry")
	proto.RegisterType((*OAuthToken)(nil), "tasks.OAuthToken")
	proto.RegisterType((*OidcToken)(nil), "tasks.OidcToken")
	proto.RegisterType((*PullMessage)(nil), "tasks.PullMessage")
	proto.RegisterType((*Attempt)(nil), "tasks.Attempt")
	proto.RegisterEnum("tasks.HttpMethod", HttpMethod_name, HttpMethod_value)
	proto.RegisterEnum("tasks.Task_View", Task_View_name, Task_View_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	Create(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	Update(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	Get(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
	Delete(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	List(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Create(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, "/tasks.TaskService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Update(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/tasks.TaskService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Get(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	out := new(GetTasksResponse)
	err := c.cc.Invoke(ctx, "/tasks.TaskService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Delete(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/tasks.TaskService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) List(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/tasks.TaskService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	Create(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	Update(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	Get(context.Context, *GetTaskRequest) (*GetTasksResponse, error)
	Delete(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	List(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasks.TaskService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Create(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasks.TaskService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Update(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasks.TaskService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Get(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasks.TaskService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Delete(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasks.TaskService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).List(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TaskService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TaskService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TaskService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TaskService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TaskService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tasks/tasks.proto",
}

func init() { proto.RegisterFile("proto/tasks/tasks.proto", fileDescriptor_tasks_81ac4b15a8391380) }

var fileDescriptor_tasks_81ac4b15a8391380 = []byte{
	// 1012 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0xb7, 0x6c, 0xd9, 0x8e, 0x4f, 0xae, 0xa7, 0x30, 0x5d, 0xa3, 0x7a, 0xc0, 0x12, 0x08, 0xc5,
	0x10, 0x0c, 0x83, 0xd3, 0x3a, 0xc0, 0xba, 0xa6, 0x40, 0x07, 0x27, 0x56, 0xe3, 0x0c, 0x49, 0x6d,
	0xc8, 0xca, 0x1e, 0xf6, 0x12, 0x30, 0x12, 0x1b, 0x0b, 0x91, 0x2d, 0x4d, 0xa4, 0x32, 0x78, 0xef,
	0xfb, 0x6a, 0xfb, 0x14, 0x7b, 0xda, 0x07, 0x19, 0x06, 0xfe, 0x91, 0x2d, 0xc5, 0x01, 0xda, 0xed,
	0xc1, 0x06, 0xf9, 0xbb, 0xdf, 0xef, 0xee, 0x48, 0x1e, 0x79, 0x82, 0xdd, 0x24, 0x8d, 0x59, 0x7c,
	0xc8, 0x30, 0xbd, 0xa3, 0xf2, 0xbf, 0x27, 0x10, 0x54, 0x17, 0x93, 0xee, 0xde, 0x6d, 0x1c, 0xdf,
	0x46, 0xe4, 0x50, 0x80, 0x37, 0xd9, 0xc7, 0x43, 0x16, 0xce, 0x09, 0x65, 0x78, 0x9e, 0x48, 0x5e,
	0xf7, 0xeb, 0x87, 0x84, 0x20, 0x4b, 0x31, 0x0b, 0xe3, 0x85, 0xb2, 0xef, 0xc8, 0x00, 0x38, 0x09,
	0xf9, 0x4f, 0x82, 0xf6, 0x1f, 0x1a, 0x6c, 0x9f, 0xa6, 0x04, 0x33, 0xe2, 0x61, 0x7a, 0xe7, 0x92,
	0x5f, 0x33, 0x42, 0x19, 0x7a, 0x06, 0x8d, 0x04, 0xa7, 0x64, 0xc1, 0x2c, 0x6d, 0x5f, 0x3b, 0x68,
	0xb9, 0x6a, 0x86, 0xf6, 0x40, 0xe7, 0xc9, 0x58, 0xd5, 0x7d, 0xed, 0xc0, 0xe8, 0x1b, 0x3d, 0x99,
	0xa6, 0x50, 0x0a, 0x03, 0x7a, 0x0d, 0xed, 0x94, 0xd0, 0x24, 0x5e, 0x50, 0xf2, 0x73, 0x48, 0x7e,
	0xb3, 0x6a, 0x82, 0xb8, 0xa3, 0x88, 0x6e, 0xc1, 0xe4, 0x96, 0x88, 0xf6, 0x53, 0x40, 0xc5, 0x34,
	0xa4, 0xc5, 0x36, 0xa1, 0x73, 0x46, 0x58, 0x21, 0x33, 0x1b, 0x81, 0xa9, 0x10, 0xba, 0x62, 0xed,
	0xc0, 0xf6, 0x55, 0x12, 0x94, 0x97, 0xc0, 0x1d, 0x16, 0x41, 0x45, 0x45, 0x60, 0x5e, 0x84, 0x34,
	0xd7, 0x4b, 0xe6, 0x0e, 0x6c, 0x17, 0x30, 0x45, 0xec, 0x40, 0xbb, 0x98, 0xad, 0xfd, 0xb7, 0x0e,
	0x3a, 0x67, 0x20, 0x04, 0xfa, 0x02, 0xcf, 0x89, 0xda, 0x18, 0x31, 0x46, 0xef, 0xa0, 0x4d, 0xfd,
	0x19, 0x09, 0xb2, 0x88, 0x78, 0xe1, 0x9c, 0xa8, 0x55, 0x77, 0x7b, 0xf2, 0x40, 0x7a, 0xf9, 0x81,
	0xf4, 0xbc, 0xfc, 0xc4, 0xdc, 0x12, 0x1f, 0x1d, 0x03, 0xf8, 0x72, 0xf1, 0x5c, 0xad, 0x7f, 0x52,
	0x5d, 0x60, 0x23, 0x07, 0xcc, 0x20, 0xa4, 0x09, 0x66, 0xfe, 0x6c, 0x48, 0x70, 0x10, 0x85, 0x0b,
	0x62, 0xd5, 0x85, 0x87, 0xe7, 0x1b, 0x1e, 0x86, 0xaa, 0x20, 0xdc, 0x0d, 0x09, 0x7a, 0x01, 0x4f,
	0x72, 0xec, 0x34, 0xce, 0x16, 0xcc, 0x6a, 0xec, 0x6b, 0x07, 0x75, 0xb7, 0x0c, 0x72, 0x56, 0x7e,
	0x6a, 0x92, 0xd5, 0x94, 0xac, 0x12, 0x88, 0xfa, 0xd0, 0xfe, 0x18, 0xa6, 0x94, 0x0d, 0x18, 0x23,
	0xf3, 0x84, 0x59, 0x5b, 0x22, 0x9d, 0x8e, 0x2a, 0x02, 0x85, 0xba, 0x25, 0x0e, 0x7a, 0x09, 0x46,
	0x84, 0xd7, 0x92, 0xd6, 0xa3, 0x92, 0x22, 0x05, 0xbd, 0x00, 0xfd, 0x9e, 0x97, 0x18, 0xec, 0x6b,
	0x07, 0x9d, 0xbe, 0x59, 0xa8, 0xc5, 0x9e, 0xa8, 0x2f, 0x61, 0x45, 0xdf, 0x83, 0x31, 0x63, 0x2c,
	0x51, 0x67, 0x6d, 0x19, 0xc2, 0x2f, 0x52, 0xe4, 0xd1, 0xda, 0x32, 0xaa, 0xb8, 0x45, 0x22, 0xd7,
	0x25, 0x59, 0x14, 0x5d, 0x12, 0x4a, 0xf1, 0x2d, 0xb1, 0xda, 0x25, 0xdd, 0x64, 0x6d, 0xe1, 0xba,
	0x02, 0xd1, 0xfe, 0x0e, 0x74, 0x1e, 0x1d, 0x7d, 0x01, 0xc6, 0xd5, 0x87, 0xe9, 0xc4, 0x39, 0x3d,
	0x7f, 0x7f, 0xee, 0x0c, 0xcd, 0x0a, 0x6a, 0x41, 0xfd, 0x64, 0x30, 0x3d, 0x3f, 0x35, 0x35, 0xb4,
	0x05, 0xfa, 0xfb, 0xab, 0x8b, 0x0b, 0xb3, 0x7a, 0xf2, 0x04, 0x8c, 0x04, 0x2f, 0xa3, 0x18, 0x07,
	0xde, 0x32, 0x21, 0xf6, 0x5f, 0x55, 0x30, 0x0a, 0x39, 0x21, 0x13, 0x6a, 0x59, 0x1a, 0xa9, 0x52,
	0xe3, 0x43, 0xf4, 0x0a, 0x80, 0x67, 0x79, 0x49, 0xd8, 0x2c, 0x0e, 0xc4, 0x35, 0xec, 0xf4, 0xb7,
	0x0b, 0xab, 0x91, 0x06, 0xb7, 0x40, 0x42, 0x6f, 0xa0, 0x39, 0x23, 0x38, 0x20, 0x29, 0xb5, 0x6a,
	0xfb, 0xb5, 0x03, 0xa3, 0xbf, 0xb7, 0xb9, 0xfa, 0xde, 0x48, 0x32, 0x9c, 0x05, 0x4b, 0x97, 0x6e,
	0xce, 0xe7, 0xb5, 0x7e, 0x13, 0x07, 0x4b, 0x51, 0x91, 0x6d, 0x57, 0x8c, 0xd1, 0x11, 0x40, 0x8c,
	0x33, 0x36, 0xf3, 0xe2, 0x3b, 0xb2, 0x50, 0x95, 0x96, 0x67, 0x30, 0x1e, 0xe4, 0x86, 0x51, 0xc5,
	0x2d, 0xd0, 0xd0, 0x4b, 0x68, 0xc5, 0x61, 0xe0, 0x4b, 0x4d, 0x43, 0x68, 0xf2, 0x03, 0x1b, 0xe7,
	0xf8, 0xa8, 0xe2, 0xae, 0x49, 0xdd, 0x63, 0x68, 0x17, 0x73, 0xe2, 0x5b, 0x71, 0x47, 0x96, 0xf9,
	0x56, 0xdc, 0x91, 0x25, 0x7a, 0x0a, 0xf5, 0x7b, 0x1c, 0x65, 0x44, 0xec, 0x42, 0xcb, 0x95, 0x93,
	0xe3, 0xea, 0x0f, 0xda, 0xc9, 0x33, 0x78, 0xca, 0x43, 0xc7, 0x69, 0xf8, 0xbb, 0x28, 0xf7, 0x6b,
	0xb9, 0x1e, 0xfb, 0x27, 0x80, 0x75, 0x86, 0xe8, 0x1b, 0xe8, 0x50, 0x92, 0xde, 0x87, 0x3e, 0x19,
	0xf8, 0xbe, 0x28, 0x66, 0xe9, 0xfc, 0x01, 0xca, 0xe3, 0x50, 0x3f, 0x4e, 0x56, 0x71, 0xc4, 0xc4,
	0x1e, 0x43, 0x6b, 0x95, 0xf9, 0x67, 0xbb, 0xea, 0xc2, 0x16, 0xce, 0x82, 0x90, 0x2c, 0xfc, 0xdc,
	0xdb, 0x6a, 0x6e, 0xbf, 0x01, 0xa3, 0x50, 0x56, 0xc8, 0x82, 0xa6, 0xaa, 0x0c, 0xe1, 0xab, 0xed,
	0xe6, 0x53, 0xbe, 0x13, 0x0c, 0xdf, 0x2a, 0x3d, 0x1f, 0xda, 0xff, 0x68, 0xd0, 0xcc, 0x6f, 0xc5,
	0xc3, 0xa7, 0x48, 0xfb, 0x8f, 0x4f, 0xd1, 0x3b, 0x68, 0xe7, 0x57, 0x5e, 0xe8, 0xab, 0x9f, 0xd6,
	0x17, 0xf9, 0x5c, 0x9f, 0x3f, 0x06, 0x9f, 0xfb, 0x14, 0x16, 0xf9, 0xe8, 0x08, 0x3a, 0xf9, 0x7c,
	0xca, 0x30, 0xcb, 0xa8, 0x7a, 0x0e, 0x8d, 0x1e, 0xef, 0x59, 0x12, 0x72, 0x1f, 0x50, 0xbe, 0xa5,
	0x00, 0xeb, 0xe2, 0x47, 0x5f, 0xc1, 0xee, 0xc8, 0xf3, 0x26, 0xd7, 0x97, 0x8e, 0x37, 0x1a, 0x0f,
	0xaf, 0xcb, 0xd7, 0x70, 0x0b, 0xf4, 0xc9, 0x78, 0xea, 0x99, 0x1a, 0x6a, 0x42, 0xed, 0xcc, 0xf1,
	0xcc, 0x2a, 0x87, 0x46, 0xce, 0x60, 0x68, 0xd6, 0x38, 0x34, 0xb9, 0xf2, 0x4c, 0x1d, 0x01, 0x34,
	0x86, 0xce, 0x85, 0xe3, 0x39, 0x66, 0x9d, 0x5f, 0xdc, 0xc9, 0xc0, 0x3b, 0x1d, 0x99, 0x0d, 0x64,
	0x40, 0x73, 0x3c, 0xf1, 0xce, 0xc7, 0x1f, 0xa6, 0x66, 0xb3, 0xff, 0x67, 0x15, 0x0c, 0xfe, 0xda,
	0x4c, 0xe5, 0x19, 0xa3, 0x1f, 0xa1, 0x21, 0x3b, 0x18, 0xb2, 0x54, 0x69, 0x6f, 0xf4, 0xd5, 0xee,
	0xf3, 0x47, 0x2c, 0xaa, 0xe1, 0x54, 0xb8, 0x03, 0xd9, 0xb1, 0x56, 0x0e, 0x36, 0xba, 0xda, 0xca,
	0xc1, 0x23, 0xad, 0xad, 0x82, 0x5e, 0x43, 0xed, 0x8c, 0x30, 0xf4, 0xa5, 0xe2, 0x94, 0x3b, 0x67,
	0x77, 0xb7, 0x0c, 0xd3, 0x72, 0xe4, 0x21, 0x89, 0xc8, 0xff, 0x8f, 0xfc, 0x16, 0x74, 0xde, 0x42,
	0x51, 0x1e, 0xe3, 0x61, 0x8f, 0xed, 0x5a, 0x9b, 0x86, 0x5c, 0x7c, 0x72, 0xf4, 0xcb, 0xab, 0xdb,
	0x90, 0xcd, 0xb2, 0x9b, 0x9e, 0x1f, 0xcf, 0x0f, 0x83, 0x2c, 0x8e, 0xb0, 0x1f, 0xc5, 0x59, 0x70,
	0x38, 0x0f, 0xfd, 0x34, 0xbe, 0xc1, 0x54, 0x7d, 0xd2, 0xc8, 0x8f, 0xa2, 0xb7, 0xe2, 0x7f, 0x52,
	0x99, 0x68, 0x37, 0x0d, 0x01, 0x1f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x46, 0x06, 0x44, 0xfd,
	0x3a, 0x09, 0x00, 0x00,
}
