// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api/pagination.proto

package api // import "github.com/duolacloud/proto/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SortDirection int32

const (
	SortDirection_ASC SortDirection = 0
	SortDirection_DSC SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DSC",
}
var SortDirection_value = map[string]int32{
	"ASC": 0,
	"DSC": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pagination_8adafe8499154b9b, []int{0}
}

type SortOption struct {
	Field                string        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction            SortDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=api.SortDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SortOption) Reset()         { *m = SortOption{} }
func (m *SortOption) String() string { return proto.CompactTextString(m) }
func (*SortOption) ProtoMessage()    {}
func (*SortOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_8adafe8499154b9b, []int{0}
}
func (m *SortOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortOption.Unmarshal(m, b)
}
func (m *SortOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortOption.Marshal(b, m, deterministic)
}
func (dst *SortOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortOption.Merge(dst, src)
}
func (m *SortOption) XXX_Size() int {
	return xxx_messageInfo_SortOption.Size(m)
}
func (m *SortOption) XXX_DiscardUnknown() {
	xxx_messageInfo_SortOption.DiscardUnknown(m)
}

var xxx_messageInfo_SortOption proto.InternalMessageInfo

func (m *SortOption) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *SortOption) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASC
}

type PageInfo struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	HasPrevious          bool     `protobuf:"varint,3,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	StartCursor          string   `protobuf:"bytes,4,opt,name=startCursor,proto3" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,5,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_8adafe8499154b9b, []int{1}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (dst *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(dst, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageInfo) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PageInfo) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *PageInfo) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

func init() {
	proto.RegisterType((*SortOption)(nil), "api.SortOption")
	proto.RegisterType((*PageInfo)(nil), "api.PageInfo")
	proto.RegisterEnum("api.SortDirection", SortDirection_name, SortDirection_value)
}

func init() {
	proto.RegisterFile("proto/api/pagination.proto", fileDescriptor_pagination_8adafe8499154b9b)
}

var fileDescriptor_pagination_8adafe8499154b9b = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0xf9, 0x87, 0xd2, 0xe6, 0x10, 0xa8, 0xb2, 0x18, 0x22, 0xc4, 0x10, 0x8a, 0x90,
	0x2a, 0x86, 0x04, 0xc1, 0xc8, 0x04, 0xe9, 0xc2, 0x02, 0x55, 0xc2, 0xc4, 0x76, 0x4d, 0xdc, 0xe4,
	0xa4, 0x90, 0xb3, 0x1c, 0x1b, 0xf1, 0x61, 0xf8, 0xb0, 0xc8, 0x2e, 0xa5, 0x65, 0xf3, 0x7b, 0xbf,
	0xe7, 0xa7, 0xa7, 0x83, 0x33, 0xa5, 0xd9, 0x70, 0x86, 0x8a, 0x32, 0x85, 0x0d, 0xf5, 0x68, 0x88,
	0xfb, 0xd4, 0x9b, 0x22, 0x44, 0x45, 0xb3, 0x57, 0x80, 0x92, 0xb5, 0x79, 0x51, 0x0e, 0x88, 0x53,
	0x18, 0xad, 0x49, 0x76, 0x75, 0x1c, 0x24, 0xc1, 0x3c, 0x2a, 0x36, 0x42, 0xdc, 0x40, 0x54, 0x93,
	0x96, 0x95, 0x8b, 0xc4, 0xff, 0x93, 0x60, 0x7e, 0x72, 0x2b, 0x52, 0x54, 0x94, 0xba, 0x9f, 0x8b,
	0x2d, 0x29, 0x76, 0xa1, 0xd9, 0x57, 0x00, 0x93, 0x25, 0x36, 0xf2, 0xa9, 0x5f, 0xb3, 0x2b, 0x35,
	0x6c, 0xb0, 0xf3, 0xa5, 0x61, 0xb1, 0x11, 0x22, 0x86, 0x71, 0x8b, 0xc3, 0xb3, 0xfc, 0x34, 0xbe,
	0x72, 0x52, 0x6c, 0xa5, 0x48, 0xe0, 0xa8, 0xc5, 0x61, 0xa9, 0xe5, 0x07, 0xb1, 0x1d, 0xe2, 0xd0,
	0xd3, 0x7d, 0xcb, 0x25, 0x06, 0x83, 0xda, 0xe4, 0x56, 0x0f, 0xac, 0xe3, 0x03, 0x3f, 0x76, 0xdf,
	0x12, 0xe7, 0x10, 0xc9, 0xbe, 0xfe, 0xe1, 0x23, 0xcf, 0x77, 0xc6, 0xf5, 0x05, 0x1c, 0xff, 0x99,
	0x2e, 0xc6, 0x10, 0x3e, 0x94, 0xf9, 0xf4, 0x9f, 0x7b, 0x2c, 0xca, 0x7c, 0x1a, 0x3c, 0x5e, 0xbd,
	0x5d, 0x36, 0x64, 0x5a, 0xbb, 0x4a, 0x2b, 0x7e, 0xcf, 0x6a, 0xcb, 0x1d, 0x56, 0x1d, 0xdb, 0x3a,
	0xfb, 0x3d, 0xe8, 0x3d, 0x2a, 0x5a, 0x1d, 0x7a, 0x79, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x70, 0xfe, 0xcc, 0x68, 0x01, 0x00, 0x00,
}
