// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api/pagination.proto

package api // import "github.com/duolacloud/microbase/proto/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

var OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderDirection) String() string {
	return proto.EnumName(OrderDirection_name, int32(x))
}
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pagination_025f75e6de850fbe, []int{0}
}

type OrderSpec struct {
	Field                string         `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction            OrderDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=api.OrderDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OrderSpec) Reset()         { *m = OrderSpec{} }
func (m *OrderSpec) String() string { return proto.CompactTextString(m) }
func (*OrderSpec) ProtoMessage()    {}
func (*OrderSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_025f75e6de850fbe, []int{0}
}
func (m *OrderSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSpec.Unmarshal(m, b)
}
func (m *OrderSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSpec.Marshal(b, m, deterministic)
}
func (dst *OrderSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSpec.Merge(dst, src)
}
func (m *OrderSpec) XXX_Size() int {
	return xxx_messageInfo_OrderSpec.Size(m)
}
func (m *OrderSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSpec proto.InternalMessageInfo

func (m *OrderSpec) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *OrderSpec) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ASC
}

type PageInfo struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	HasPrevious          bool     `protobuf:"varint,3,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	StartCursor          string   `protobuf:"bytes,4,opt,name=startCursor,proto3" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,5,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_025f75e6de850fbe, []int{1}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (dst *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(dst, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageInfo) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PageInfo) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *PageInfo) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

type ConnectionQuery struct {
	HasFirst             bool         `protobuf:"varint,1,opt,name=hasFirst,proto3" json:"hasFirst,omitempty"`
	First                int32        `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	HasLast              bool         `protobuf:"varint,3,opt,name=hasLast,proto3" json:"hasLast,omitempty"`
	Last                 int32        `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	HasAfter             bool         `protobuf:"varint,5,opt,name=hasAfter,proto3" json:"hasAfter,omitempty"`
	After                string       `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	HasBefore            bool         `protobuf:"varint,7,opt,name=hasBefore,proto3" json:"hasBefore,omitempty"`
	Before               string       `protobuf:"bytes,8,opt,name=before,proto3" json:"before,omitempty"`
	NeedTotal            bool         `protobuf:"varint,9,opt,name=needTotal,proto3" json:"needTotal,omitempty"`
	Fields               []string     `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter               string       `protobuf:"bytes,11,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders               []*OrderSpec `protobuf:"bytes,12,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConnectionQuery) Reset()         { *m = ConnectionQuery{} }
func (m *ConnectionQuery) String() string { return proto.CompactTextString(m) }
func (*ConnectionQuery) ProtoMessage()    {}
func (*ConnectionQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_025f75e6de850fbe, []int{2}
}
func (m *ConnectionQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionQuery.Unmarshal(m, b)
}
func (m *ConnectionQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionQuery.Marshal(b, m, deterministic)
}
func (dst *ConnectionQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionQuery.Merge(dst, src)
}
func (m *ConnectionQuery) XXX_Size() int {
	return xxx_messageInfo_ConnectionQuery.Size(m)
}
func (m *ConnectionQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionQuery proto.InternalMessageInfo

func (m *ConnectionQuery) GetHasFirst() bool {
	if m != nil {
		return m.HasFirst
	}
	return false
}

func (m *ConnectionQuery) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ConnectionQuery) GetHasLast() bool {
	if m != nil {
		return m.HasLast
	}
	return false
}

func (m *ConnectionQuery) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *ConnectionQuery) GetHasAfter() bool {
	if m != nil {
		return m.HasAfter
	}
	return false
}

func (m *ConnectionQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *ConnectionQuery) GetHasBefore() bool {
	if m != nil {
		return m.HasBefore
	}
	return false
}

func (m *ConnectionQuery) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func (m *ConnectionQuery) GetNeedTotal() bool {
	if m != nil {
		return m.NeedTotal
	}
	return false
}

func (m *ConnectionQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ConnectionQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ConnectionQuery) GetOrders() []*OrderSpec {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderSpec)(nil), "api.OrderSpec")
	proto.RegisterType((*PageInfo)(nil), "api.PageInfo")
	proto.RegisterType((*ConnectionQuery)(nil), "api.ConnectionQuery")
	proto.RegisterEnum("api.OrderDirection", OrderDirection_name, OrderDirection_value)
}

func init() {
	proto.RegisterFile("proto/api/pagination.proto", fileDescriptor_pagination_025f75e6de850fbe)
}

var fileDescriptor_pagination_025f75e6de850fbe = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x35, 0xcd, 0x7e, 0x24, 0x77, 0x65, 0x2d, 0xa3, 0xc8, 0x50, 0x7c, 0x08, 0x2b, 0xc8, 0x22,
	0xb8, 0xc1, 0xfa, 0xe8, 0x53, 0x9b, 0x2a, 0x08, 0xa2, 0x35, 0xdb, 0x27, 0xdf, 0x6e, 0x92, 0xc9,
	0x66, 0x20, 0xcd, 0x84, 0x99, 0x89, 0xe8, 0x7f, 0xf1, 0x3f, 0xf9, 0x97, 0x64, 0xee, 0x64, 0x37,
	0xed, 0x5b, 0xce, 0x39, 0x73, 0x0e, 0x27, 0xf7, 0x5e, 0xb8, 0xe8, 0xb5, 0xb2, 0x2a, 0xc5, 0x5e,
	0xa6, 0x3d, 0x1e, 0x64, 0x87, 0x56, 0xaa, 0x6e, 0x47, 0x24, 0x0b, 0xb1, 0x97, 0x9b, 0x3b, 0x88,
	0xbf, 0xeb, 0x4a, 0xe8, 0x7d, 0x2f, 0x4a, 0xf6, 0x02, 0xe6, 0xb5, 0x14, 0x6d, 0xc5, 0x83, 0x24,
	0xd8, 0xc6, 0xb9, 0x07, 0xec, 0x3d, 0xc4, 0x95, 0xd4, 0xa2, 0x74, 0x56, 0x7e, 0x96, 0x04, 0xdb,
	0xf5, 0xe5, 0xf3, 0x1d, 0xf6, 0x72, 0x47, 0xc6, 0x9b, 0xa3, 0x94, 0x4f, 0xaf, 0x36, 0x7f, 0x03,
	0x88, 0x6e, 0xf1, 0x20, 0xbe, 0x74, 0xb5, 0x72, 0xa9, 0x56, 0x59, 0x6c, 0x29, 0x35, 0xcc, 0x3d,
	0x60, 0x1c, 0x96, 0x0d, 0x9a, 0x6f, 0xe2, 0xb7, 0xa5, 0xcc, 0x28, 0x3f, 0x42, 0x96, 0xc0, 0xaa,
	0x41, 0x73, 0xab, 0xc5, 0x2f, 0xa9, 0x06, 0xc3, 0x43, 0x52, 0x1f, 0x52, 0xee, 0x85, 0xb1, 0xa8,
	0x6d, 0x36, 0x68, 0xa3, 0x34, 0x9f, 0x51, 0xdb, 0x87, 0x14, 0x7b, 0x05, 0xb1, 0xe8, 0xaa, 0x51,
	0x9f, 0x93, 0x3e, 0x11, 0x9b, 0x7f, 0x67, 0xf0, 0x2c, 0x53, 0x5d, 0xe7, 0xdb, 0xfe, 0x18, 0x84,
	0xfe, 0xc3, 0x2e, 0x20, 0x6a, 0xd0, 0x7c, 0x96, 0xda, 0x58, 0x2a, 0x1a, 0xe5, 0x27, 0xec, 0xe7,
	0xe2, 0x04, 0xd7, 0x74, 0x9e, 0x7b, 0x30, 0xfe, 0xc1, 0x57, 0x34, 0x76, 0xec, 0x78, 0x84, 0x8c,
	0xc1, 0xac, 0x75, 0xf4, 0x8c, 0x9e, 0xd3, 0xf7, 0x98, 0x7f, 0x55, 0x5b, 0xe1, 0x0b, 0xf9, 0x7c,
	0xc2, 0x2e, 0x1f, 0x49, 0x58, 0xf8, 0xb9, 0x13, 0x70, 0xff, 0xd0, 0xa0, 0xb9, 0x16, 0xb5, 0xd2,
	0x82, 0x2f, 0xc9, 0x32, 0x11, 0xec, 0x25, 0x2c, 0x0a, 0x2f, 0x45, 0x64, 0x1a, 0x91, 0x73, 0x75,
	0x42, 0x54, 0x77, 0x34, 0xf1, 0xd8, 0xbb, 0x4e, 0x84, 0x73, 0xd1, 0x52, 0x0d, 0x87, 0x24, 0x74,
	0x2e, 0x8f, 0x3c, 0xdf, 0xba, 0x0a, 0x2b, 0x9f, 0xe6, 0x11, 0x7b, 0x03, 0x0b, 0xe5, 0xb6, 0x6c,
	0xf8, 0xd3, 0x24, 0xdc, 0xae, 0x2e, 0xd7, 0xd3, 0xe2, 0xdd, 0xc5, 0xe4, 0xa3, 0xfa, 0xf6, 0x35,
	0xac, 0x1f, 0x5f, 0x03, 0x5b, 0x42, 0x78, 0xb5, 0xcf, 0xce, 0x9f, 0xb0, 0x08, 0x66, 0x37, 0x9f,
	0xf6, 0xd9, 0x79, 0x70, 0x9d, 0xfe, 0x7c, 0x77, 0x90, 0xb6, 0x19, 0x8a, 0x5d, 0xa9, 0xee, 0xd3,
	0x6a, 0x50, 0x2d, 0x96, 0xad, 0x1a, 0xaa, 0xf4, 0x5e, 0x96, 0x5a, 0x15, 0x68, 0x44, 0x7a, 0x3a,
	0xd7, 0x8f, 0xd8, 0xcb, 0x62, 0x41, 0xf0, 0xc3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xd3,
	0xa5, 0xf5, 0xc6, 0x02, 0x00, 0x00,
}
