// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/paginator/pagination.proto

package paginator // import "github.com/duolacloud/microbase/proto/paginator"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

var OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderDirection) String() string {
	return proto.EnumName(OrderDirection_name, int32(x))
}
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{0}
}

type OrderSpec struct {
	Field                string         `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction            OrderDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=api.OrderDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OrderSpec) Reset()         { *m = OrderSpec{} }
func (m *OrderSpec) String() string { return proto.CompactTextString(m) }
func (*OrderSpec) ProtoMessage()    {}
func (*OrderSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{0}
}
func (m *OrderSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSpec.Unmarshal(m, b)
}
func (m *OrderSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSpec.Marshal(b, m, deterministic)
}
func (dst *OrderSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSpec.Merge(dst, src)
}
func (m *OrderSpec) XXX_Size() int {
	return xxx_messageInfo_OrderSpec.Size(m)
}
func (m *OrderSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSpec proto.InternalMessageInfo

func (m *OrderSpec) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *OrderSpec) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ASC
}

type PageInfo struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	HasPrevious          bool     `protobuf:"varint,3,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	StartCursor          string   `protobuf:"bytes,4,opt,name=startCursor,proto3" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,5,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{1}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (dst *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(dst, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageInfo) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PageInfo) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *PageInfo) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

type ConnectionQuery struct {
	HasFirst             bool         `protobuf:"varint,1,opt,name=hasFirst,proto3" json:"hasFirst,omitempty"`
	First                int32        `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	HasLast              bool         `protobuf:"varint,3,opt,name=hasLast,proto3" json:"hasLast,omitempty"`
	Last                 int32        `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	HasAfter             bool         `protobuf:"varint,5,opt,name=hasAfter,proto3" json:"hasAfter,omitempty"`
	After                string       `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	HasBefore            bool         `protobuf:"varint,7,opt,name=hasBefore,proto3" json:"hasBefore,omitempty"`
	Before               string       `protobuf:"bytes,8,opt,name=before,proto3" json:"before,omitempty"`
	NeedTotal            bool         `protobuf:"varint,9,opt,name=needTotal,proto3" json:"needTotal,omitempty"`
	Fields               []string     `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter               string       `protobuf:"bytes,11,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders               []*OrderSpec `protobuf:"bytes,12,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConnectionQuery) Reset()         { *m = ConnectionQuery{} }
func (m *ConnectionQuery) String() string { return proto.CompactTextString(m) }
func (*ConnectionQuery) ProtoMessage()    {}
func (*ConnectionQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{2}
}
func (m *ConnectionQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionQuery.Unmarshal(m, b)
}
func (m *ConnectionQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionQuery.Marshal(b, m, deterministic)
}
func (dst *ConnectionQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionQuery.Merge(dst, src)
}
func (m *ConnectionQuery) XXX_Size() int {
	return xxx_messageInfo_ConnectionQuery.Size(m)
}
func (m *ConnectionQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionQuery proto.InternalMessageInfo

func (m *ConnectionQuery) GetHasFirst() bool {
	if m != nil {
		return m.HasFirst
	}
	return false
}

func (m *ConnectionQuery) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ConnectionQuery) GetHasLast() bool {
	if m != nil {
		return m.HasLast
	}
	return false
}

func (m *ConnectionQuery) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *ConnectionQuery) GetHasAfter() bool {
	if m != nil {
		return m.HasAfter
	}
	return false
}

func (m *ConnectionQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *ConnectionQuery) GetHasBefore() bool {
	if m != nil {
		return m.HasBefore
	}
	return false
}

func (m *ConnectionQuery) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func (m *ConnectionQuery) GetNeedTotal() bool {
	if m != nil {
		return m.NeedTotal
	}
	return false
}

func (m *ConnectionQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ConnectionQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ConnectionQuery) GetOrders() []*OrderSpec {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Connection struct {
	PageInfo             *PageInfo `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Edges                *Edge     `protobuf:"bytes,3,opt,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{3}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (dst *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(dst, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *Connection) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Connection) GetEdges() *Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Edge struct {
	Node                 *any.Any `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_f97e98a416e48214, []int{4}
}
func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (dst *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(dst, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetNode() *any.Any {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Edge) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderSpec)(nil), "api.OrderSpec")
	proto.RegisterType((*PageInfo)(nil), "api.PageInfo")
	proto.RegisterType((*ConnectionQuery)(nil), "api.ConnectionQuery")
	proto.RegisterType((*Connection)(nil), "api.Connection")
	proto.RegisterType((*Edge)(nil), "api.Edge")
	proto.RegisterEnum("api.OrderDirection", OrderDirection_name, OrderDirection_value)
}

func init() {
	proto.RegisterFile("proto/paginator/pagination.proto", fileDescriptor_pagination_f97e98a416e48214)
}

var fileDescriptor_pagination_f97e98a416e48214 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xa5, 0x4d, 0xda, 0x4d, 0xa6, 0x50, 0x56, 0x66, 0x85, 0xc2, 0x0a, 0x89, 0xa8, 0x48, 0xa8,
	0x70, 0x48, 0x45, 0x39, 0xa1, 0x3d, 0x75, 0xbb, 0x8b, 0x40, 0x42, 0xb0, 0xa4, 0x7b, 0xe2, 0xe6,
	0x26, 0x6e, 0x1a, 0x29, 0x6b, 0x47, 0xb6, 0x83, 0xe8, 0xbf, 0xf0, 0x4f, 0xfc, 0x12, 0xf2, 0x4c,
	0xd2, 0x94, 0x9b, 0xdf, 0x7b, 0x7e, 0x93, 0xf1, 0xcc, 0x0b, 0xc4, 0xb5, 0x56, 0x56, 0x2d, 0x6a,
	0x5e, 0x94, 0x92, 0x5b, 0xa5, 0xbb, 0x53, 0xa9, 0x64, 0x82, 0x12, 0xf3, 0x78, 0x5d, 0x5e, 0xbe,
	0x28, 0x94, 0x2a, 0x2a, 0xb1, 0x40, 0x6a, 0xdb, 0xec, 0x16, 0x5c, 0x1e, 0x48, 0x9f, 0xdd, 0x43,
	0xf8, 0x5d, 0xe7, 0x42, 0x6f, 0x6a, 0x91, 0xb1, 0x0b, 0x18, 0xed, 0x4a, 0x51, 0xe5, 0xd1, 0x20,
	0x1e, 0xcc, 0xc3, 0x94, 0x00, 0x7b, 0x0f, 0x61, 0x5e, 0x6a, 0x91, 0xb9, 0xaa, 0xd1, 0x30, 0x1e,
	0xcc, 0xa7, 0xcb, 0x67, 0x09, 0xaf, 0xcb, 0x04, 0x8d, 0x37, 0x9d, 0x94, 0xf6, 0xb7, 0x66, 0x7f,
	0x06, 0x10, 0xdc, 0xf1, 0x42, 0x7c, 0x91, 0x3b, 0xe5, 0xaa, 0x5a, 0x65, 0x79, 0x85, 0x55, 0xbd,
	0x94, 0x00, 0x8b, 0xe0, 0x6c, 0xcf, 0xcd, 0x37, 0xf1, 0xdb, 0x62, 0xcd, 0x20, 0xed, 0x20, 0x8b,
	0x61, 0xb2, 0xe7, 0xe6, 0x4e, 0x8b, 0x5f, 0xa5, 0x6a, 0x4c, 0xe4, 0xa1, 0x7a, 0x4a, 0xb9, 0x1b,
	0xc6, 0x72, 0x6d, 0xd7, 0x8d, 0x36, 0x4a, 0x47, 0x3e, 0x76, 0x7b, 0x4a, 0xb1, 0x97, 0x10, 0x0a,
	0x99, 0xb7, 0xfa, 0x08, 0xf5, 0x9e, 0x98, 0xfd, 0x1d, 0xc2, 0xd3, 0xb5, 0x92, 0x92, 0xba, 0xfd,
	0xd1, 0x08, 0x7d, 0x60, 0x97, 0x10, 0xec, 0xb9, 0xf9, 0x54, 0x6a, 0x63, 0xb1, 0xd1, 0x20, 0x3d,
	0x62, 0x9a, 0x8b, 0x13, 0x5c, 0xa7, 0xa3, 0x94, 0x40, 0xfb, 0x82, 0xaf, 0xdc, 0xd8, 0xb6, 0xc7,
	0x0e, 0x32, 0x06, 0x7e, 0xe5, 0x68, 0x1f, 0xaf, 0xe3, 0xb9, 0xad, 0xbf, 0xda, 0x59, 0x41, 0x0d,
	0x51, 0x7d, 0xc4, 0xae, 0x3e, 0x47, 0x61, 0x4c, 0x73, 0x47, 0xe0, 0xde, 0xb0, 0xe7, 0xe6, 0x5a,
	0xec, 0x94, 0x16, 0xd1, 0x19, 0x5a, 0x7a, 0x82, 0x3d, 0x87, 0xf1, 0x96, 0xa4, 0x00, 0x4d, 0x2d,
	0x72, 0x2e, 0x29, 0x44, 0x7e, 0x8f, 0x13, 0x0f, 0xc9, 0x75, 0x24, 0x9c, 0x0b, 0x97, 0x6a, 0x22,
	0x88, 0x3d, 0xe7, 0x22, 0x44, 0x7c, 0xe5, 0x5a, 0x98, 0x50, 0x35, 0x42, 0xec, 0x0d, 0x8c, 0x95,
	0xdb, 0xb2, 0x89, 0x1e, 0xc7, 0xde, 0x7c, 0xb2, 0x9c, 0xf6, 0x8b, 0x77, 0x89, 0x49, 0x5b, 0x75,
	0x26, 0x01, 0xfa, 0x81, 0xb2, 0xb7, 0x10, 0xd4, 0xed, 0xf6, 0x71, 0x96, 0x93, 0xe5, 0x13, 0xf4,
	0x75, 0x91, 0x48, 0x8f, 0x72, 0x1f, 0x8e, 0xe1, 0x69, 0x38, 0x5e, 0xc1, 0x48, 0xe4, 0x85, 0xa0,
	0xe5, 0x4f, 0x96, 0x21, 0xba, 0x6f, 0xf3, 0x42, 0xa4, 0xc4, 0xcf, 0x3e, 0x83, 0xef, 0x20, 0x9b,
	0x83, 0x2f, 0x55, 0x2e, 0xda, 0xaf, 0x5c, 0x24, 0x14, 0xf4, 0xa4, 0x0b, 0x7a, 0xb2, 0x92, 0x87,
	0x14, 0x6f, 0xb8, 0x17, 0x66, 0x14, 0x87, 0x21, 0xbd, 0x90, 0xd0, 0xbb, 0xd7, 0x30, 0xfd, 0x3f,
	0xc7, 0xec, 0x0c, 0xbc, 0xd5, 0x66, 0x7d, 0xfe, 0x88, 0x05, 0xe0, 0xdf, 0xdc, 0x6e, 0xd6, 0xe7,
	0x83, 0xeb, 0xab, 0x9f, 0x1f, 0x8b, 0xd2, 0xee, 0x9b, 0x6d, 0x92, 0xa9, 0x87, 0x45, 0xde, 0xa8,
	0x8a, 0x67, 0x95, 0x6a, 0xf2, 0xc5, 0x43, 0x99, 0x69, 0xb5, 0xe5, 0xa6, 0xfd, 0xb7, 0xfa, 0x3f,
	0xf1, 0xea, 0x78, 0xda, 0x8e, 0x51, 0xfa, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x9a, 0xd5,
	0x74, 0xad, 0x03, 0x00, 0x00,
}
