// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pagination/pagination.proto

package pagination // import "github.com/duolacloud/microbase/proto/pagination"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

var OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderDirection) String() string {
	return proto.EnumName(OrderDirection_name, int32(x))
}
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{0}
}

type CursorDirection int32

const (
	CursorDirection_before CursorDirection = 0
	CursorDirection_after  CursorDirection = 1
)

var CursorDirection_name = map[int32]string{
	0: "before",
	1: "after",
}
var CursorDirection_value = map[string]int32{
	"before": 0,
	"after":  1,
}

func (x CursorDirection) String() string {
	return proto.EnumName(CursorDirection_name, int32(x))
}
func (CursorDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{1}
}

type Order struct {
	Field                string         `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction            OrderDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=pagination.OrderDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Order) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ASC
}

type PageInfo struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	HasPrevious          bool     `protobuf:"varint,3,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	StartCursor          string   `protobuf:"bytes,4,opt,name=startCursor,proto3" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,5,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{1}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (dst *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(dst, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageInfo) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PageInfo) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *PageInfo) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

type ConnectionQuery struct {
	HasFirst             bool     `protobuf:"varint,1,opt,name=hasFirst,proto3" json:"hasFirst,omitempty"`
	First                int32    `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	HasLast              bool     `protobuf:"varint,3,opt,name=hasLast,proto3" json:"hasLast,omitempty"`
	Last                 int32    `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	HasAfter             bool     `protobuf:"varint,5,opt,name=hasAfter,proto3" json:"hasAfter,omitempty"`
	After                string   `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	HasBefore            bool     `protobuf:"varint,7,opt,name=hasBefore,proto3" json:"hasBefore,omitempty"`
	Before               string   `protobuf:"bytes,8,opt,name=before,proto3" json:"before,omitempty"`
	NeedTotal            bool     `protobuf:"varint,9,opt,name=needTotal,proto3" json:"needTotal,omitempty"`
	Fields               []string `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter               string   `protobuf:"bytes,11,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders               []*Order `protobuf:"bytes,12,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionQuery) Reset()         { *m = ConnectionQuery{} }
func (m *ConnectionQuery) String() string { return proto.CompactTextString(m) }
func (*ConnectionQuery) ProtoMessage()    {}
func (*ConnectionQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{2}
}
func (m *ConnectionQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionQuery.Unmarshal(m, b)
}
func (m *ConnectionQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionQuery.Marshal(b, m, deterministic)
}
func (dst *ConnectionQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionQuery.Merge(dst, src)
}
func (m *ConnectionQuery) XXX_Size() int {
	return xxx_messageInfo_ConnectionQuery.Size(m)
}
func (m *ConnectionQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionQuery proto.InternalMessageInfo

func (m *ConnectionQuery) GetHasFirst() bool {
	if m != nil {
		return m.HasFirst
	}
	return false
}

func (m *ConnectionQuery) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ConnectionQuery) GetHasLast() bool {
	if m != nil {
		return m.HasLast
	}
	return false
}

func (m *ConnectionQuery) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *ConnectionQuery) GetHasAfter() bool {
	if m != nil {
		return m.HasAfter
	}
	return false
}

func (m *ConnectionQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *ConnectionQuery) GetHasBefore() bool {
	if m != nil {
		return m.HasBefore
	}
	return false
}

func (m *ConnectionQuery) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func (m *ConnectionQuery) GetNeedTotal() bool {
	if m != nil {
		return m.NeedTotal
	}
	return false
}

func (m *ConnectionQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ConnectionQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ConnectionQuery) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Connection struct {
	PageInfo             *PageInfo `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Edges                []*Edge   `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{3}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (dst *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(dst, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *Connection) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Connection) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Edge struct {
	Node                 *any.Any `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{4}
}
func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (dst *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(dst, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetNode() *any.Any {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Edge) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type PageQuery struct {
	PageNo               int64    `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders               []*Order `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	Fields               []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{5}
}
func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (dst *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(dst, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *PageQuery) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *PageQuery) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *PageQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

// 游标查询
type ListQuery struct {
	Direction            CursorDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=pagination.CursorDirection" json:"direction,omitempty"`
	Filter               string          `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Size                 int32           `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Cursor               string          `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	NeedTotal            bool            `protobuf:"varint,5,opt,name=needTotal,proto3" json:"needTotal,omitempty"`
	Orders               []*Order        `protobuf:"bytes,6,rep,name=orders,proto3" json:"orders,omitempty"`
	Fields               []string        `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{6}
}
func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (dst *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(dst, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetDirection() CursorDirection {
	if m != nil {
		return m.Direction
	}
	return CursorDirection_before
}

func (m *ListQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListQuery) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListQuery) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListQuery) GetNeedTotal() bool {
	if m != nil {
		return m.NeedTotal
	}
	return false
}

func (m *ListQuery) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *ListQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ListResponse struct {
	Items                []*any.Any `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PageInfo             *PageInfo  `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_87d46e9608e18755, []int{7}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetItems() []*any.Any {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListResponse) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "pagination.Order")
	proto.RegisterType((*PageInfo)(nil), "pagination.PageInfo")
	proto.RegisterType((*ConnectionQuery)(nil), "pagination.ConnectionQuery")
	proto.RegisterType((*Connection)(nil), "pagination.Connection")
	proto.RegisterType((*Edge)(nil), "pagination.Edge")
	proto.RegisterType((*PageQuery)(nil), "pagination.PageQuery")
	proto.RegisterType((*ListQuery)(nil), "pagination.ListQuery")
	proto.RegisterType((*ListResponse)(nil), "pagination.ListResponse")
	proto.RegisterEnum("pagination.OrderDirection", OrderDirection_name, OrderDirection_value)
	proto.RegisterEnum("pagination.CursorDirection", CursorDirection_name, CursorDirection_value)
}

func init() {
	proto.RegisterFile("proto/pagination/pagination.proto", fileDescriptor_pagination_87d46e9608e18755)
}

var fileDescriptor_pagination_87d46e9608e18755 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xae, 0x63, 0x3b, 0xb1, 0x27, 0x55, 0x9b, 0xdf, 0xaa, 0xfa, 0x61, 0x5a, 0x0e, 0x21, 0x48,
	0x28, 0xf4, 0x90, 0xa0, 0x72, 0x01, 0x55, 0x1c, 0xda, 0xb4, 0x08, 0xa4, 0xaa, 0x14, 0x17, 0x09,
	0x89, 0x0b, 0xda, 0xc4, 0x1b, 0xc7, 0x92, 0xeb, 0x8d, 0xbc, 0x6b, 0x44, 0x2b, 0x1e, 0x85, 0xa7,
	0xe2, 0x35, 0x78, 0x09, 0xb4, 0xb3, 0xeb, 0x78, 0x53, 0x8a, 0xe8, 0xcd, 0xdf, 0xfc, 0xf3, 0x37,
	0x33, 0xdf, 0x2c, 0x3c, 0x5e, 0x96, 0x5c, 0xf2, 0xf1, 0x92, 0xa6, 0x59, 0x41, 0x65, 0xc6, 0x0b,
	0xeb, 0x73, 0x84, 0x3e, 0x02, 0x8d, 0x65, 0xf7, 0x61, 0xca, 0x79, 0x9a, 0xb3, 0x31, 0x7a, 0xa6,
	0xd5, 0x7c, 0x4c, 0x8b, 0x6b, 0x1d, 0x36, 0xf8, 0x04, 0xfe, 0xfb, 0x32, 0x61, 0x25, 0xd9, 0x01,
	0x7f, 0x9e, 0xb1, 0x3c, 0x89, 0x9c, 0xbe, 0x33, 0x0c, 0x63, 0x0d, 0xc8, 0x4b, 0x08, 0x93, 0xac,
	0x64, 0x33, 0x55, 0x26, 0x6a, 0xf5, 0x9d, 0xe1, 0xd6, 0xc1, 0xee, 0xc8, 0xfa, 0x17, 0xe6, 0x9e,
	0xd4, 0x11, 0x71, 0x13, 0x3c, 0xf8, 0xe1, 0x40, 0x70, 0x41, 0x53, 0xf6, 0xae, 0x98, 0x73, 0x55,
	0x5c, 0x72, 0x49, 0x73, 0x2c, 0xee, 0xc6, 0x1a, 0x90, 0x08, 0x3a, 0x0b, 0x2a, 0xce, 0xd9, 0x37,
	0x89, 0xa5, 0x83, 0xb8, 0x86, 0xa4, 0x0f, 0xdd, 0x05, 0x15, 0x17, 0x25, 0xfb, 0x9a, 0xf1, 0x4a,
	0x44, 0x2e, 0x7a, 0x6d, 0x93, 0x8a, 0x10, 0x92, 0x96, 0x72, 0x52, 0x95, 0x82, 0x97, 0x91, 0x87,
	0xa4, 0x6d, 0x13, 0x79, 0x04, 0x21, 0x2b, 0x12, 0xe3, 0xf7, 0xd1, 0xdf, 0x18, 0x06, 0x3f, 0x5b,
	0xb0, 0x3d, 0xe1, 0x45, 0xa1, 0xd9, 0x7e, 0xa8, 0x58, 0x79, 0x4d, 0x76, 0x21, 0x58, 0x50, 0xf1,
	0x26, 0x2b, 0x85, 0x44, 0xa2, 0x41, 0xbc, 0xc2, 0x7a, 0x3c, 0xca, 0xa1, 0x98, 0xfa, 0xb1, 0x06,
	0xa6, 0x83, 0x33, 0x2a, 0xa4, 0xe1, 0x58, 0x43, 0x42, 0xc0, 0xcb, 0x95, 0xd9, 0xc3, 0x70, 0xfc,
	0x36, 0xf5, 0x8f, 0xe6, 0x92, 0x69, 0x42, 0xba, 0x3e, 0x62, 0x55, 0x9f, 0xa2, 0xa3, 0xad, 0xc7,
	0x8f, 0x40, 0xf5, 0xb0, 0xa0, 0xe2, 0x98, 0xcd, 0x79, 0xc9, 0xa2, 0x0e, 0xa6, 0x34, 0x06, 0xf2,
	0x3f, 0xb4, 0xa7, 0xda, 0x15, 0x60, 0x92, 0x41, 0x2a, 0xab, 0x60, 0x2c, 0xf9, 0x88, 0x13, 0x0f,
	0x75, 0xd6, 0xca, 0xa0, 0xb2, 0x70, 0xb7, 0x22, 0x82, 0xbe, 0xab, 0xb2, 0x34, 0xd2, 0xf6, 0x5c,
	0x51, 0xe8, 0xea, 0x6a, 0x1a, 0x91, 0x67, 0xd0, 0xe6, 0x6a, 0xcb, 0x22, 0xda, 0xec, 0xbb, 0xc3,
	0xee, 0xc1, 0x7f, 0x7f, 0xec, 0x3f, 0x36, 0x01, 0x83, 0xef, 0x00, 0xcd, 0x4c, 0xc9, 0x73, 0x08,
	0x96, 0x46, 0x00, 0x38, 0xce, 0xee, 0xc1, 0x8e, 0x9d, 0x5a, 0x8b, 0x23, 0x5e, 0x45, 0x35, 0x32,
	0x69, 0xd9, 0x32, 0x79, 0x0a, 0x3e, 0x4b, 0x52, 0xa6, 0x64, 0xa0, 0xfe, 0xdf, 0xb3, 0x8b, 0x9c,
	0x26, 0x29, 0x8b, 0xb5, 0x7b, 0xf0, 0x16, 0x3c, 0x05, 0xc9, 0x10, 0xbc, 0x82, 0x27, 0x6c, 0xf5,
	0x4f, 0x2d, 0xfe, 0x51, 0x2d, 0xfe, 0xd1, 0x51, 0x71, 0x1d, 0x63, 0x84, 0x6a, 0x79, 0xa6, 0xf5,
	0xd1, 0xd2, 0x2d, 0x6b, 0xa4, 0xb4, 0x1b, 0x2a, 0x7a, 0x5a, 0x16, 0x0f, 0xa0, 0xa3, 0x18, 0x7e,
	0x29, 0xb8, 0x91, 0x6f, 0x5b, 0xc1, 0x73, 0x4e, 0xf6, 0x20, 0x44, 0x87, 0xc8, 0x6e, 0x98, 0xd1,
	0x05, 0xf6, 0x72, 0x99, 0xdd, 0x30, 0x6b, 0x9c, 0xee, 0x5f, 0xc6, 0xe9, 0xfd, 0x63, 0x9c, 0xd6,
	0xa6, 0x7c, 0x7b, 0x53, 0x83, 0x5f, 0x0e, 0x84, 0x67, 0x99, 0x90, 0x9a, 0xde, 0x2b, 0xfb, 0x44,
	0x1d, 0x3c, 0xd1, 0x3d, 0xbb, 0xa6, 0x16, 0xfc, 0x5d, 0x37, 0x6a, 0x71, 0x6c, 0xad, 0x71, 0x24,
	0xe0, 0x61, 0x4f, 0xae, 0x16, 0xaf, 0x30, 0xfd, 0xcc, 0xec, 0x5b, 0x33, 0x68, 0x5d, 0x6c, 0xfe,
	0x6d, 0xb1, 0x35, 0xdd, 0xb6, 0xef, 0xdf, 0x6d, 0x67, 0xad, 0xdb, 0x1c, 0x36, 0x55, 0xb3, 0x31,
	0x13, 0x4b, 0x5e, 0x08, 0x46, 0xf6, 0xc1, 0xcf, 0x24, 0xbb, 0x12, 0x91, 0x83, 0x15, 0xef, 0xde,
	0xaf, 0x0e, 0x59, 0x93, 0x60, 0xeb, 0x3e, 0x12, 0xdc, 0x7f, 0x02, 0x5b, 0xeb, 0x6f, 0x1a, 0xe9,
	0x80, 0x7b, 0x74, 0x39, 0xe9, 0x6d, 0x90, 0x00, 0xbc, 0x93, 0xd3, 0xcb, 0x49, 0xcf, 0xd9, 0x1f,
	0xc2, 0xf6, 0xad, 0xa9, 0x12, 0xa8, 0x6f, 0xb1, 0xb7, 0x41, 0x42, 0x73, 0xcb, 0x3d, 0xe7, 0xf8,
	0xf5, 0xe7, 0xc3, 0x34, 0x93, 0x8b, 0x6a, 0x3a, 0x9a, 0xf1, 0xab, 0x71, 0x52, 0xf1, 0x9c, 0xce,
	0x72, 0x5e, 0x25, 0xe3, 0xab, 0x6c, 0x56, 0xf2, 0x29, 0x15, 0xe6, 0x51, 0xb6, 0xde, 0xef, 0xc3,
	0xe6, 0x73, 0xda, 0x46, 0xe7, 0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x4a, 0xdb, 0xac,
	0xf0, 0x05, 0x00, 0x00,
}
