// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/search/search.proto

package search

import (
	fmt "fmt"
	pagination "github.com/duolacloud/microbase/proto/pagination"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SearchService service

func NewSearchServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SearchService service

type SearchService interface {
	Upsert(ctx context.Context, in *UpsertDocumentRequest, opts ...client.CallOption) (*UpsertDocumentResponse, error)
	BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, opts ...client.CallOption) (*BatchUpsertDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...client.CallOption) (*Document, error)
	BatchGet(ctx context.Context, in *BatchGetDocumentRequest, opts ...client.CallOption) (*BatchGetDocumentResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	// 列表查询模式查询结果
	Connection(ctx context.Context, in *pagination.ConnectionQuery, opts ...client.CallOption) (*pagination.Connection, error)
}

type searchService struct {
	c    client.Client
	name string
}

func NewSearchService(name string, c client.Client) SearchService {
	return &searchService{
		c:    c,
		name: name,
	}
}

func (c *searchService) Upsert(ctx context.Context, in *UpsertDocumentRequest, opts ...client.CallOption) (*UpsertDocumentResponse, error) {
	req := c.c.NewRequest(c.name, "SearchService.Upsert", in)
	out := new(UpsertDocumentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, opts ...client.CallOption) (*BatchUpsertDocumentResponse, error) {
	req := c.c.NewRequest(c.name, "SearchService.BatchUpsert", in)
	out := new(BatchUpsertDocumentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) Get(ctx context.Context, in *GetDocumentRequest, opts ...client.CallOption) (*Document, error) {
	req := c.c.NewRequest(c.name, "SearchService.Get", in)
	out := new(Document)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) BatchGet(ctx context.Context, in *BatchGetDocumentRequest, opts ...client.CallOption) (*BatchGetDocumentResponse, error) {
	req := c.c.NewRequest(c.name, "SearchService.BatchGet", in)
	out := new(BatchGetDocumentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "SearchService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) Connection(ctx context.Context, in *pagination.ConnectionQuery, opts ...client.CallOption) (*pagination.Connection, error) {
	req := c.c.NewRequest(c.name, "SearchService.Connection", in)
	out := new(pagination.Connection)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceHandler interface {
	Upsert(context.Context, *UpsertDocumentRequest, *UpsertDocumentResponse) error
	BatchUpsert(context.Context, *BatchUpsertDocumentRequest, *BatchUpsertDocumentResponse) error
	Get(context.Context, *GetDocumentRequest, *Document) error
	BatchGet(context.Context, *BatchGetDocumentRequest, *BatchGetDocumentResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	// 列表查询模式查询结果
	Connection(context.Context, *pagination.ConnectionQuery, *pagination.Connection) error
}

func RegisterSearchServiceHandler(s server.Server, hdlr SearchServiceHandler, opts ...server.HandlerOption) error {
	type searchService interface {
		Upsert(ctx context.Context, in *UpsertDocumentRequest, out *UpsertDocumentResponse) error
		BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, out *BatchUpsertDocumentResponse) error
		Get(ctx context.Context, in *GetDocumentRequest, out *Document) error
		BatchGet(ctx context.Context, in *BatchGetDocumentRequest, out *BatchGetDocumentResponse) error
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
		Connection(ctx context.Context, in *pagination.ConnectionQuery, out *pagination.Connection) error
	}
	type SearchService struct {
		searchService
	}
	h := &searchServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SearchService{h}, opts...))
}

type searchServiceHandler struct {
	SearchServiceHandler
}

func (h *searchServiceHandler) Upsert(ctx context.Context, in *UpsertDocumentRequest, out *UpsertDocumentResponse) error {
	return h.SearchServiceHandler.Upsert(ctx, in, out)
}

func (h *searchServiceHandler) BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, out *BatchUpsertDocumentResponse) error {
	return h.SearchServiceHandler.BatchUpsert(ctx, in, out)
}

func (h *searchServiceHandler) Get(ctx context.Context, in *GetDocumentRequest, out *Document) error {
	return h.SearchServiceHandler.Get(ctx, in, out)
}

func (h *searchServiceHandler) BatchGet(ctx context.Context, in *BatchGetDocumentRequest, out *BatchGetDocumentResponse) error {
	return h.SearchServiceHandler.BatchGet(ctx, in, out)
}

func (h *searchServiceHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SearchServiceHandler.Search(ctx, in, out)
}

func (h *searchServiceHandler) Connection(ctx context.Context, in *pagination.ConnectionQuery, out *pagination.Connection) error {
	return h.SearchServiceHandler.Connection(ctx, in, out)
}

// Api Endpoints for IndexService service

func NewIndexServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for IndexService service

type IndexService interface {
	Create(ctx context.Context, in *CreateIndexRequest, opts ...client.CallOption) (*CreateIndexResponse, error)
	Delete(ctx context.Context, in *DeleteIndexRequest, opts ...client.CallOption) (*DeleteIndexResponse, error)
}

type indexService struct {
	c    client.Client
	name string
}

func NewIndexService(name string, c client.Client) IndexService {
	return &indexService{
		c:    c,
		name: name,
	}
}

func (c *indexService) Create(ctx context.Context, in *CreateIndexRequest, opts ...client.CallOption) (*CreateIndexResponse, error) {
	req := c.c.NewRequest(c.name, "IndexService.Create", in)
	out := new(CreateIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexService) Delete(ctx context.Context, in *DeleteIndexRequest, opts ...client.CallOption) (*DeleteIndexResponse, error) {
	req := c.c.NewRequest(c.name, "IndexService.Delete", in)
	out := new(DeleteIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IndexService service

type IndexServiceHandler interface {
	Create(context.Context, *CreateIndexRequest, *CreateIndexResponse) error
	Delete(context.Context, *DeleteIndexRequest, *DeleteIndexResponse) error
}

func RegisterIndexServiceHandler(s server.Server, hdlr IndexServiceHandler, opts ...server.HandlerOption) error {
	type indexService interface {
		Create(ctx context.Context, in *CreateIndexRequest, out *CreateIndexResponse) error
		Delete(ctx context.Context, in *DeleteIndexRequest, out *DeleteIndexResponse) error
	}
	type IndexService struct {
		indexService
	}
	h := &indexServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&IndexService{h}, opts...))
}

type indexServiceHandler struct {
	IndexServiceHandler
}

func (h *indexServiceHandler) Create(ctx context.Context, in *CreateIndexRequest, out *CreateIndexResponse) error {
	return h.IndexServiceHandler.Create(ctx, in, out)
}

func (h *indexServiceHandler) Delete(ctx context.Context, in *DeleteIndexRequest, out *DeleteIndexResponse) error {
	return h.IndexServiceHandler.Delete(ctx, in, out)
}
