// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/search/search.proto

package search // import "duolacloud.com/duolacloud/microbase/proto/search"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pagination "github.com/duolacloud/microbase/proto/pagination"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Index struct {
	IndexSetting         *IndexSetting  `protobuf:"bytes,1,opt,name=indexSetting,proto3" json:"indexSetting,omitempty"`
	Fields               []*FieldConfig `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{0}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (dst *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(dst, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetIndexSetting() *IndexSetting {
	if m != nil {
		return m.IndexSetting
	}
	return nil
}

func (m *Index) GetFields() []*FieldConfig {
	if m != nil {
		return m.Fields
	}
	return nil
}

type IndexSetting struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexSetting) Reset()         { *m = IndexSetting{} }
func (m *IndexSetting) String() string { return proto.CompactTextString(m) }
func (*IndexSetting) ProtoMessage()    {}
func (*IndexSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{1}
}
func (m *IndexSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSetting.Unmarshal(m, b)
}
func (m *IndexSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSetting.Marshal(b, m, deterministic)
}
func (dst *IndexSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSetting.Merge(dst, src)
}
func (m *IndexSetting) XXX_Size() int {
	return xxx_messageInfo_IndexSetting.Size(m)
}
func (m *IndexSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSetting.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSetting proto.InternalMessageInfo

type FieldConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Analyzer             string   `protobuf:"bytes,3,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldConfig) Reset()         { *m = FieldConfig{} }
func (m *FieldConfig) String() string { return proto.CompactTextString(m) }
func (*FieldConfig) ProtoMessage()    {}
func (*FieldConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{2}
}
func (m *FieldConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldConfig.Unmarshal(m, b)
}
func (m *FieldConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldConfig.Marshal(b, m, deterministic)
}
func (dst *FieldConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldConfig.Merge(dst, src)
}
func (m *FieldConfig) XXX_Size() int {
	return xxx_messageInfo_FieldConfig.Size(m)
}
func (m *FieldConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FieldConfig proto.InternalMessageInfo

func (m *FieldConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldConfig) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

type CreateIndexRequest struct {
	Index                *Index   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIndexRequest) Reset()         { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()    {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{3}
}
func (m *CreateIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndexRequest.Unmarshal(m, b)
}
func (m *CreateIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndexRequest.Marshal(b, m, deterministic)
}
func (dst *CreateIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndexRequest.Merge(dst, src)
}
func (m *CreateIndexRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIndexRequest.Size(m)
}
func (m *CreateIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndexRequest proto.InternalMessageInfo

func (m *CreateIndexRequest) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type CreateIndexResponse struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIndexResponse) Reset()         { *m = CreateIndexResponse{} }
func (m *CreateIndexResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIndexResponse) ProtoMessage()    {}
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{4}
}
func (m *CreateIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndexResponse.Unmarshal(m, b)
}
func (m *CreateIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndexResponse.Marshal(b, m, deterministic)
}
func (dst *CreateIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndexResponse.Merge(dst, src)
}
func (m *CreateIndexResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIndexResponse.Size(m)
}
func (m *CreateIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndexResponse proto.InternalMessageInfo

func (m *CreateIndexResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

type DeleteIndexRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexRequest) Reset()         { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()    {}
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{5}
}
func (m *DeleteIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexRequest.Unmarshal(m, b)
}
func (m *DeleteIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexRequest.Merge(dst, src)
}
func (m *DeleteIndexRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexRequest.Size(m)
}
func (m *DeleteIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexRequest proto.InternalMessageInfo

func (m *DeleteIndexRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type DeleteIndexResponse struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexResponse) Reset()         { *m = DeleteIndexResponse{} }
func (m *DeleteIndexResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexResponse) ProtoMessage()    {}
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{6}
}
func (m *DeleteIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexResponse.Unmarshal(m, b)
}
func (m *DeleteIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexResponse.Merge(dst, src)
}
func (m *DeleteIndexResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexResponse.Size(m)
}
func (m *DeleteIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexResponse proto.InternalMessageInfo

func (m *DeleteIndexResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

type Document struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index                string            `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Fields               map[string]string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{7}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (dst *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(dst, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Document) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Document) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpsertDocumentRequest struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpsertDocumentRequest) Reset()         { *m = UpsertDocumentRequest{} }
func (m *UpsertDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertDocumentRequest) ProtoMessage()    {}
func (*UpsertDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{8}
}
func (m *UpsertDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertDocumentRequest.Unmarshal(m, b)
}
func (m *UpsertDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *UpsertDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertDocumentRequest.Merge(dst, src)
}
func (m *UpsertDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertDocumentRequest.Size(m)
}
func (m *UpsertDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertDocumentRequest proto.InternalMessageInfo

func (m *UpsertDocumentRequest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type UpsertDocumentResponse struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertDocumentResponse) Reset()         { *m = UpsertDocumentResponse{} }
func (m *UpsertDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertDocumentResponse) ProtoMessage()    {}
func (*UpsertDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{9}
}
func (m *UpsertDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertDocumentResponse.Unmarshal(m, b)
}
func (m *UpsertDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *UpsertDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertDocumentResponse.Merge(dst, src)
}
func (m *UpsertDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertDocumentResponse.Size(m)
}
func (m *UpsertDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertDocumentResponse proto.InternalMessageInfo

func (m *UpsertDocumentResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

type BatchUpsertDocumentRequest struct {
	Document             []*Document `protobuf:"bytes,1,rep,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BatchUpsertDocumentRequest) Reset()         { *m = BatchUpsertDocumentRequest{} }
func (m *BatchUpsertDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*BatchUpsertDocumentRequest) ProtoMessage()    {}
func (*BatchUpsertDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{10}
}
func (m *BatchUpsertDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpsertDocumentRequest.Unmarshal(m, b)
}
func (m *BatchUpsertDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpsertDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *BatchUpsertDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpsertDocumentRequest.Merge(dst, src)
}
func (m *BatchUpsertDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_BatchUpsertDocumentRequest.Size(m)
}
func (m *BatchUpsertDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpsertDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpsertDocumentRequest proto.InternalMessageInfo

func (m *BatchUpsertDocumentRequest) GetDocument() []*Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BatchUpsertDocumentResponse struct {
	Items                []*UpsertDocumentRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BatchUpsertDocumentResponse) Reset()         { *m = BatchUpsertDocumentResponse{} }
func (m *BatchUpsertDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*BatchUpsertDocumentResponse) ProtoMessage()    {}
func (*BatchUpsertDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{11}
}
func (m *BatchUpsertDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpsertDocumentResponse.Unmarshal(m, b)
}
func (m *BatchUpsertDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpsertDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *BatchUpsertDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpsertDocumentResponse.Merge(dst, src)
}
func (m *BatchUpsertDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_BatchUpsertDocumentResponse.Size(m)
}
func (m *BatchUpsertDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpsertDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpsertDocumentResponse proto.InternalMessageInfo

func (m *BatchUpsertDocumentResponse) GetItems() []*UpsertDocumentRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentRequest) Reset()         { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()    {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{12}
}
func (m *GetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentRequest.Unmarshal(m, b)
}
func (m *GetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *GetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentRequest.Merge(dst, src)
}
func (m *GetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentRequest.Size(m)
}
func (m *GetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentRequest proto.InternalMessageInfo

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BatchGetDocumentRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetDocumentRequest) Reset()         { *m = BatchGetDocumentRequest{} }
func (m *BatchGetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetDocumentRequest) ProtoMessage()    {}
func (*BatchGetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{13}
}
func (m *BatchGetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetDocumentRequest.Unmarshal(m, b)
}
func (m *BatchGetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *BatchGetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetDocumentRequest.Merge(dst, src)
}
func (m *BatchGetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetDocumentRequest.Size(m)
}
func (m *BatchGetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetDocumentRequest proto.InternalMessageInfo

func (m *BatchGetDocumentRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type BatchGetDocumentResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BatchGetDocumentResponse) Reset()         { *m = BatchGetDocumentResponse{} }
func (m *BatchGetDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetDocumentResponse) ProtoMessage()    {}
func (*BatchGetDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{14}
}
func (m *BatchGetDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetDocumentResponse.Unmarshal(m, b)
}
func (m *BatchGetDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *BatchGetDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetDocumentResponse.Merge(dst, src)
}
func (m *BatchGetDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetDocumentResponse.Size(m)
}
func (m *BatchGetDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetDocumentResponse proto.InternalMessageInfo

func (m *BatchGetDocumentResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type SearchRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CurrentPage          int32    `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{15}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *SearchRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SearchResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total                int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{16}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (dst *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(dst, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *SearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type DeleteDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentRequest) Reset()         { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()    {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{17}
}
func (m *DeleteDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentRequest.Unmarshal(m, b)
}
func (m *DeleteDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentRequest.Merge(dst, src)
}
func (m *DeleteDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentRequest.Size(m)
}
func (m *DeleteDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentRequest proto.InternalMessageInfo

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentResponse) Reset()         { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()    {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_9a2c96ff0b70d0eb, []int{18}
}
func (m *DeleteDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentResponse.Unmarshal(m, b)
}
func (m *DeleteDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentResponse.Merge(dst, src)
}
func (m *DeleteDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentResponse.Size(m)
}
func (m *DeleteDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentResponse proto.InternalMessageInfo

func (m *DeleteDocumentResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func init() {
	proto.RegisterType((*Index)(nil), "search.Index")
	proto.RegisterType((*IndexSetting)(nil), "search.IndexSetting")
	proto.RegisterType((*FieldConfig)(nil), "search.FieldConfig")
	proto.RegisterType((*CreateIndexRequest)(nil), "search.CreateIndexRequest")
	proto.RegisterType((*CreateIndexResponse)(nil), "search.CreateIndexResponse")
	proto.RegisterType((*DeleteIndexRequest)(nil), "search.DeleteIndexRequest")
	proto.RegisterType((*DeleteIndexResponse)(nil), "search.DeleteIndexResponse")
	proto.RegisterType((*Document)(nil), "search.Document")
	proto.RegisterMapType((map[string]string)(nil), "search.Document.FieldsEntry")
	proto.RegisterType((*UpsertDocumentRequest)(nil), "search.UpsertDocumentRequest")
	proto.RegisterType((*UpsertDocumentResponse)(nil), "search.UpsertDocumentResponse")
	proto.RegisterType((*BatchUpsertDocumentRequest)(nil), "search.BatchUpsertDocumentRequest")
	proto.RegisterType((*BatchUpsertDocumentResponse)(nil), "search.BatchUpsertDocumentResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "search.GetDocumentRequest")
	proto.RegisterType((*BatchGetDocumentRequest)(nil), "search.BatchGetDocumentRequest")
	proto.RegisterType((*BatchGetDocumentResponse)(nil), "search.BatchGetDocumentResponse")
	proto.RegisterType((*SearchRequest)(nil), "search.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "search.SearchResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "search.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "search.DeleteDocumentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Upsert(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*UpsertDocumentResponse, error)
	BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, opts ...grpc.CallOption) (*BatchUpsertDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	BatchGet(ctx context.Context, in *BatchGetDocumentRequest, opts ...grpc.CallOption) (*BatchGetDocumentResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// 列表查询模式查询结果
	Connection(ctx context.Context, in *pagination.ConnectionQuery, opts ...grpc.CallOption) (*pagination.Connection, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Upsert(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*UpsertDocumentResponse, error) {
	out := new(UpsertDocumentResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) BatchUpsert(ctx context.Context, in *BatchUpsertDocumentRequest, opts ...grpc.CallOption) (*BatchUpsertDocumentResponse, error) {
	out := new(BatchUpsertDocumentResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/BatchUpsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/search.SearchService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) BatchGet(ctx context.Context, in *BatchGetDocumentRequest, opts ...grpc.CallOption) (*BatchGetDocumentResponse, error) {
	out := new(BatchGetDocumentResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/BatchGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Connection(ctx context.Context, in *pagination.ConnectionQuery, opts ...grpc.CallOption) (*pagination.Connection, error) {
	out := new(pagination.Connection)
	err := c.cc.Invoke(ctx, "/search.SearchService/Connection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Upsert(context.Context, *UpsertDocumentRequest) (*UpsertDocumentResponse, error)
	BatchUpsert(context.Context, *BatchUpsertDocumentRequest) (*BatchUpsertDocumentResponse, error)
	Get(context.Context, *GetDocumentRequest) (*Document, error)
	BatchGet(context.Context, *BatchGetDocumentRequest) (*BatchGetDocumentResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// 列表查询模式查询结果
	Connection(context.Context, *pagination.ConnectionQuery) (*pagination.Connection, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Upsert(ctx, req.(*UpsertDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/BatchUpsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).BatchUpsert(ctx, req.(*BatchUpsertDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Get(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/BatchGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).BatchGet(ctx, req.(*BatchGetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Connection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pagination.ConnectionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Connection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Connection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Connection(ctx, req.(*pagination.ConnectionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SearchService_Upsert_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _SearchService_BatchUpsert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SearchService_Get_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _SearchService_BatchGet_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "Connection",
			Handler:    _SearchService_Connection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search/search.proto",
}

// IndexServiceClient is the client API for IndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexServiceClient interface {
	Create(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	Delete(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
}

type indexServiceClient struct {
	cc *grpc.ClientConn
}

func NewIndexServiceClient(cc *grpc.ClientConn) IndexServiceClient {
	return &indexServiceClient{cc}
}

func (c *indexServiceClient) Create(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, "/search.IndexService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) Delete(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, "/search.IndexService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServiceServer is the server API for IndexService service.
type IndexServiceServer interface {
	Create(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	Delete(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
}

func RegisterIndexServiceServer(s *grpc.Server, srv IndexServiceServer) {
	s.RegisterService(&_IndexService_serviceDesc, srv)
}

func _IndexService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.IndexService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).Create(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.IndexService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).Delete(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IndexService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.IndexService",
	HandlerType: (*IndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _IndexService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IndexService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search/search.proto",
}

func init() { proto.RegisterFile("proto/search/search.proto", fileDescriptor_search_9a2c96ff0b70d0eb) }

var fileDescriptor_search_9a2c96ff0b70d0eb = []byte{
	// 749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5f, 0x4f, 0x13, 0x41,
	0x10, 0x6f, 0x7b, 0xb4, 0xb6, 0x53, 0x20, 0x64, 0x81, 0x5a, 0xaf, 0xfe, 0xc1, 0xc5, 0x04, 0x02,
	0xa6, 0x4d, 0x8a, 0x46, 0xaa, 0x4f, 0x52, 0x90, 0xc0, 0x8b, 0x72, 0x8d, 0xc6, 0xf8, 0x42, 0x96,
	0xbb, 0xa1, 0x6c, 0x68, 0xf7, 0xea, 0xdd, 0x1e, 0x5a, 0x3e, 0x89, 0x5f, 0xc4, 0x37, 0x3f, 0x9c,
	0xb9, 0xdb, 0xdb, 0xeb, 0xf5, 0x1f, 0x18, 0x9f, 0x3a, 0x3b, 0xf3, 0xdb, 0xdf, 0x6f, 0x76, 0x66,
	0x7a, 0x03, 0x8f, 0x06, 0x9e, 0x2b, 0xdd, 0x86, 0x8f, 0xcc, 0xb3, 0xaf, 0xe2, 0x9f, 0x7a, 0xe4,
	0x23, 0x05, 0x75, 0x32, 0xdf, 0x77, 0xb9, 0xbc, 0x0a, 0x2e, 0xea, 0xb6, 0xdb, 0x6f, 0x38, 0x81,
	0xdb, 0x63, 0x76, 0xcf, 0x0d, 0x9c, 0x46, 0x9f, 0xdb, 0x9e, 0x7b, 0xc1, 0x7c, 0x6c, 0x28, 0x8a,
	0x01, 0xeb, 0x72, 0xc1, 0x24, 0x77, 0x45, 0xca, 0x54, 0x54, 0x54, 0x40, 0xfe, 0x44, 0x38, 0xf8,
	0x93, 0xec, 0xc3, 0x22, 0x0f, 0x8d, 0x0e, 0x4a, 0xc9, 0x45, 0xb7, 0x9a, 0xdd, 0xc8, 0x6e, 0x97,
	0x9b, 0x6b, 0xf5, 0x58, 0xf8, 0x24, 0x15, 0xb3, 0xc6, 0x90, 0x64, 0x17, 0x0a, 0x97, 0x1c, 0x7b,
	0x8e, 0x5f, 0xcd, 0x6d, 0x18, 0xdb, 0xe5, 0xe6, 0xaa, 0xbe, 0xf3, 0x21, 0xf4, 0xb6, 0x5d, 0x71,
	0xc9, 0xbb, 0x56, 0x0c, 0xa1, 0xcb, 0xb0, 0x98, 0xa6, 0xa2, 0x67, 0x50, 0x4e, 0xc1, 0x08, 0x81,
	0x05, 0xc1, 0xfa, 0x18, 0xa9, 0x97, 0xac, 0xc8, 0x0e, 0x7d, 0x72, 0x38, 0xc0, 0x6a, 0x4e, 0xf9,
	0x42, 0x9b, 0x98, 0x50, 0x64, 0x82, 0xf5, 0x86, 0xb7, 0xe8, 0x55, 0x8d, 0xc8, 0x9f, 0x9c, 0x69,
	0x0b, 0x48, 0xdb, 0x43, 0x26, 0x31, 0x12, 0xb2, 0xf0, 0x7b, 0x80, 0xbe, 0x24, 0x9b, 0x90, 0x8f,
	0xb2, 0x8e, 0x1f, 0xb6, 0x34, 0xf6, 0x30, 0x4b, 0xc5, 0xe8, 0x16, 0xac, 0x8e, 0x5d, 0xf5, 0x07,
	0xae, 0xf0, 0x91, 0xac, 0x80, 0xc1, 0xec, 0xeb, 0xe8, 0x66, 0xd1, 0x0a, 0x4d, 0xba, 0x03, 0xe4,
	0x10, 0x7b, 0x38, 0xa1, 0xb1, 0x96, 0xd6, 0x28, 0xa5, 0x48, 0xc7, 0xb0, 0x73, 0x49, 0x7f, 0x67,
	0xa1, 0x78, 0xe8, 0xda, 0x41, 0x1f, 0x85, 0x24, 0xcb, 0x90, 0xe3, 0x4e, 0x4c, 0x94, 0xe3, 0xce,
	0x88, 0x3b, 0x97, 0xe2, 0x4e, 0x6a, 0x63, 0xa4, 0x6a, 0xf3, 0x2a, 0xe9, 0xc7, 0x42, 0xd4, 0x8f,
	0xc7, 0xfa, 0xa9, 0x9a, 0x5b, 0x35, 0xc6, 0x3f, 0x12, 0xd2, 0x1b, 0xea, 0xc6, 0x98, 0xad, 0xb8,
	0x11, 0xca, 0x1d, 0x66, 0x77, 0x8d, 0xc3, 0x58, 0x3f, 0x34, 0xc3, 0x04, 0x6e, 0x58, 0x2f, 0xd0,
	0x7d, 0x50, 0x87, 0xb7, 0xb9, 0xfd, 0x2c, 0x3d, 0x82, 0xf5, 0xcf, 0x03, 0x1f, 0x3d, 0xa9, 0x05,
	0x74, 0x3d, 0x5e, 0x42, 0xd1, 0x89, 0x5d, 0x71, 0xd9, 0x57, 0x26, 0x73, 0xb1, 0x12, 0x04, 0xdd,
	0x81, 0xca, 0x24, 0xcd, 0xdc, 0x52, 0x9d, 0x82, 0x79, 0xc0, 0xa4, 0x7d, 0xf5, 0x2f, 0xba, 0xc6,
	0x3d, 0xba, 0x16, 0xd4, 0x66, 0x72, 0xc5, 0xe2, 0x7b, 0x90, 0xe7, 0x12, 0xfb, 0x7e, 0xcc, 0xf4,
	0x44, 0x33, 0xcd, 0x94, 0xb6, 0x14, 0x96, 0xbe, 0x00, 0x72, 0x8c, 0x53, 0x79, 0x4d, 0xf4, 0x94,
	0xee, 0xc2, 0xc3, 0x48, 0x79, 0x06, 0x74, 0x05, 0x0c, 0xee, 0x28, 0xcd, 0x92, 0x15, 0x9a, 0xf4,
	0x14, 0xaa, 0xd3, 0xe0, 0x38, 0xc7, 0x3a, 0x94, 0xf4, 0x73, 0xfc, 0xb9, 0x2f, 0x1e, 0x41, 0x28,
	0x87, 0xa5, 0x4e, 0x14, 0xd5, 0x72, 0x55, 0x78, 0x70, 0x8d, 0xc3, 0x1f, 0xae, 0xa7, 0xd3, 0xd3,
	0x47, 0xf2, 0x1c, 0x16, 0xed, 0xc0, 0xf3, 0x50, 0xc8, 0xf3, 0x01, 0xeb, 0xaa, 0xee, 0xe7, 0xad,
	0x72, 0xec, 0xfb, 0xc4, 0xba, 0x48, 0x6a, 0x50, 0x0a, 0x43, 0xe7, 0x3e, 0xbf, 0x55, 0x93, 0x98,
	0xb7, 0x8a, 0xa1, 0xa3, 0xc3, 0x6f, 0x91, 0x7e, 0x81, 0x65, 0x2d, 0xf5, 0x7f, 0xc9, 0x86, 0x83,
	0x27, 0x5d, 0xc9, 0x7a, 0x91, 0xb4, 0x61, 0xa9, 0x03, 0xdd, 0x82, 0x75, 0xf5, 0xaf, 0xba, 0xaf,
	0xc8, 0x3b, 0x50, 0x99, 0x04, 0xce, 0x1b, 0xab, 0xe6, 0x1f, 0x43, 0x17, 0xa6, 0x83, 0xde, 0x0d,
	0xb7, 0x91, 0x9c, 0x40, 0x41, 0x35, 0x9a, 0xdc, 0xdd, 0x78, 0xf3, 0xe9, 0xbc, 0xb0, 0x12, 0xa3,
	0x19, 0xf2, 0x15, 0xca, 0xa9, 0x39, 0x23, 0x54, 0x5f, 0x98, 0x3f, 0xc8, 0xe6, 0xe6, 0x9d, 0x98,
	0x84, 0xf9, 0x35, 0x18, 0xc7, 0x28, 0x89, 0xa9, 0xd1, 0xd3, 0xf3, 0x64, 0x4e, 0x55, 0x98, 0x66,
	0xc8, 0x47, 0x28, 0xea, 0x89, 0x22, 0xcf, 0xc6, 0x94, 0x66, 0x10, 0x6c, 0xcc, 0x07, 0x24, 0x79,
	0xb4, 0xa0, 0xa0, 0xaa, 0x47, 0xd6, 0x35, 0x7a, 0x6c, 0xcc, 0xcc, 0xca, 0xa4, 0x3b, 0xb9, 0xda,
	0x06, 0x68, 0xbb, 0x42, 0xa0, 0x1d, 0xee, 0x26, 0x52, 0xab, 0xa7, 0x16, 0xd5, 0xc8, 0x7f, 0x16,
	0xa0, 0x37, 0x34, 0x2b, 0xb3, 0x83, 0x34, 0xd3, 0xfc, 0x95, 0x4d, 0xb6, 0x8b, 0xea, 0x5e, 0x1b,
	0x0a, 0xea, 0x7b, 0x3e, 0xaa, 0xcd, 0xf4, 0x6a, 0x30, 0x6b, 0x33, 0x63, 0xa9, 0xd4, 0x0a, 0x6a,
	0x80, 0x46, 0x24, 0xd3, 0xdf, 0xfe, 0x11, 0xc9, 0x8c, 0x6f, 0x3d, 0xcd, 0x1c, 0xb4, 0xbe, 0xbd,
	0x19, 0x6d, 0xe8, 0xfb, 0x16, 0xb6, 0x62, 0x7a, 0xa7, 0x7e, 0x2e, 0x0a, 0x91, 0x73, 0xef, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xed, 0xa6, 0xad, 0x11, 0x08, 0x00, 0x00,
}
